"""analytics_pipeline_cqrs_tables

Revision ID: 547066039c38
Revises: e5a8f219b431
Create Date: 2026-09-14 10:48:34.284695

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '547066039c38'
down_revision: Union[str, None] = 'e5a8f219b431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_booking_id'), 'analytics_events', ['booking_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_id'), 'analytics_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
    op.create_index('ix_analytics_events_name_time', 'analytics_events', ['event_name', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_occurred_at'), 'analytics_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_venue_id'), 'analytics_events', ['venue_id'], unique=False)
    op.create_index('ix_analytics_events_venue_time', 'analytics_events', ['venue_id', 'occurred_at'], unique=False)
    op.create_table('daily_booking_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('accepted_requests', sa.Integer(), nullable=False),
    sa.Column('rejected_requests', sa.Integer(), nullable=False),
    sa.Column('confirmed_bookings', sa.Integer(), nullable=False),
    sa.Column('completed_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('total_response_time_seconds', sa.BigInteger(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('slot_hours_booked', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_booking_stats_date'), 'daily_booking_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_booking_stats_venue_id'), 'daily_booking_stats', ['venue_id'], unique=False)
    op.create_index('uq_daily_booking_stats_date_venue', 'daily_booking_stats', ['date', sa.literal_column("COALESCE(venue_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    op.create_table('daily_revenue_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('gross_merchandise_value_paise', sa.BigInteger(), nullable=False),
    sa.Column('platform_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('owner_payout_paise', sa.BigInteger(), nullable=False),
    sa.Column('refunds_paise', sa.BigInteger(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_revenue_stats_date'), 'daily_revenue_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_revenue_stats_venue_id'), 'daily_revenue_stats', ['venue_id'], unique=False)
    op.create_index('uq_daily_revenue_stats_date_venue', 'daily_revenue_stats', ['date', sa.literal_column("COALESCE(venue_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    op.create_table('daily_search_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('total_searches', sa.Integer(), nullable=False),
    sa.Column('total_venue_views', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_search_stats_date'), 'daily_search_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_search_stats_venue_id'), 'daily_search_stats', ['venue_id'], unique=False)
    op.create_index('uq_daily_search_stats_date_venue', 'daily_search_stats', ['date', sa.literal_column("COALESCE(venue_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_daily_search_stats_date_venue', table_name='daily_search_stats')
    op.drop_index(op.f('ix_daily_search_stats_venue_id'), table_name='daily_search_stats')
    op.drop_index(op.f('ix_daily_search_stats_date'), table_name='daily_search_stats')
    op.drop_table('daily_search_stats')
    op.drop_index('uq_daily_revenue_stats_date_venue', table_name='daily_revenue_stats')
    op.drop_index(op.f('ix_daily_revenue_stats_venue_id'), table_name='daily_revenue_stats')
    op.drop_index(op.f('ix_daily_revenue_stats_date'), table_name='daily_revenue_stats')
    op.drop_table('daily_revenue_stats')
    op.drop_index('uq_daily_booking_stats_date_venue', table_name='daily_booking_stats')
    op.drop_index(op.f('ix_daily_booking_stats_venue_id'), table_name='daily_booking_stats')
    op.drop_index(op.f('ix_daily_booking_stats_date'), table_name='daily_booking_stats')
    op.drop_table('daily_booking_stats')
    op.drop_index('ix_analytics_events_venue_time', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_venue_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_occurred_at'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_name_time', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_booking_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
