"""add daily_engagement_stats table

Revision ID: e9ecc0d19b2f
Revises: 547066039c38
Create Date: 2026-09-14 08:03:33.883750

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e9ecc0d19b2f'
down_revision: Union[str, None] = '547066039c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_engagement_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('wishlist_adds', sa.Integer(), nullable=False),
    sa.Column('wishlist_removes', sa.Integer(), nullable=False),
    sa.Column('reviews_submitted', sa.Integer(), nullable=False),
    sa.Column('avg_review_rating', sa.Float(), nullable=False),
    sa.Column('availability_checks', sa.Integer(), nullable=False),
    sa.Column('pricing_previews', sa.Integer(), nullable=False),
    sa.Column('booking_detail_views', sa.Integer(), nullable=False),
    sa.Column('unique_engaged_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_engagement_stats_date'), 'daily_engagement_stats', ['date'], unique=False)
    op.create_index(op.f('ix_daily_engagement_stats_venue_id'), 'daily_engagement_stats', ['venue_id'], unique=False)
    op.create_index('uq_daily_engagement_stats_date_venue', 'daily_engagement_stats', ['date', sa.literal_column("COALESCE(venue_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_daily_engagement_stats_date_venue', table_name='daily_engagement_stats')
    op.drop_index(op.f('ix_daily_engagement_stats_venue_id'), table_name='daily_engagement_stats')
    op.drop_index(op.f('ix_daily_engagement_stats_date'), table_name='daily_engagement_stats')
    op.drop_table('daily_engagement_stats')
    # ### end Alembic commands ###
